-- ── TABLA DE PRECIOS (carga manual) ──────────────────────────────────────────
--
-- Precio de cada plan, para poder calcular la FACTURACIÓN de un alumno y, con
-- ella, el MARGEN de su profesor (facturación de sus alumnos − lo que se le paga).
--
-- Se carga y se actualiza A MANO desde Supabase. No hay cron ni sincronización
-- con WooCommerce: se decidió (11/08/2026) dejar el sync automático para más
-- adelante. Lo que quedó construido de aquel camino y sigue sirviendo:
--   · lib/wooPrices.ts               — normalización a €/mes y prorrateo
--   · /api/admin/woo-price-probe     — lectura de solo lectura del catálogo de Woo
--
-- CÓMO SE EMPAREJA UN ALUMNO CON SU FILA
--
-- Por SUBCADENA sobre `students.product_name` (o `plan` como respaldo), sin
-- distinguir mayúsculas ni el sufijo de variación. GANA EL PATRÓN MÁS LARGO.
--
-- Eso último no es un detalle: "Inglés general" es subcadena de "Curso de inglés
-- general - 2h semanales, B1", de "Intensivos Inglés general" y de "Matricula DRC
-- Academy - Inglés General". Sin la regla del más largo, una sola fila corta se
-- comería medio catálogo. COROLARIO: no borres las filas largas pensando que la
-- corta las cubre — las cubre, pero con el precio equivocado.
--
-- QUÉ SIGNIFICA `active = false`
--
-- "Este producto NO se factura", no "ignorá esta fila". La diferencia importa y
-- se descubrió con un caso real: "Matricula DRC Academy - Inglés General" es un
-- cobro de alta única, no un plan mensual. Si simplemente no se cargara, el
-- alumno que la tiene (Manuel Gómez) caería en la fila "Inglés general" — más
-- corta pero también subcadena de su producto — y se le facturaría un plan
-- mensual completo todos los meses a su profesor, que es exactamente lo que se
-- quería evitar.
--
-- Por eso la fila SÍ se carga, con active=false: gana el match por ser la más
-- larga y corta ahí, devolviendo "facturación desconocida" en vez de un número
-- inventado.
--
-- billing_months: sobre cuántos meses se reparte el precio.
--   · Suscripción → 1 (el precio ya es mensual).
--   · Pago único  → la duración del curso (intensivos, empresas). El importe se
--     imputa price/billing_months a cada mes de la ventana, y 0 fuera de ella.
--   · EXCEPCIÓN: si el alumno tiene `students.company_plan_months` (duración real
--     contratada, extraída de la variación de Woo por productUtils), MANDA ESE
--     VALOR. Un dato real por alumno siempre gana a la constante de la tabla.

create table if not exists product_prices (
  id                    bigint generated by default as identity primary key,
  product_name_contains text    not null,
  price                 numeric not null check (price >= 0),
  billing_months        int     not null default 1 check (billing_months >= 1),
  active                boolean not null default true,
  notes                 text,
  created_at            timestamptz default now()
);

-- Herramienta interna: mismo criterio que el resto de las tablas del proyecto.
alter table product_prices disable row level security;

-- Un patrón, una fila. En minúsculas porque el emparejado es case-insensitive:
-- sin esto, "intensivo PET" e "Intensivo PET" convivirían con precios distintos y
-- cuál gana dependería del orden de lectura.
create unique index if not exists product_prices_pattern_uniq
  on product_prices (lower(product_name_contains));

-- ── CARGA ────────────────────────────────────────────────────────────────────
--
-- Los 35 patrones que cubren los 188 alumnos de hoy están en
-- `product_prices_plantilla.csv`, en la raíz del repo, con la columna
-- `precio_cobrado_eur` VACÍA para completar. Se importa desde Supabase con
-- Table Editor → Import data from CSV, mapeando:
--
--   patron_nombre_producto → product_name_contains
--   precio_cobrado_eur     → price
--   meses_que_cubre        → billing_months
--   active                 → active
--   notas                  → notes
--
-- Las columnas `alumnos_hoy` y `tipo` del CSV son informativas (para decidir por
-- dónde empezar) y no tienen destino en la tabla.
--
-- Un precio que falte no rompe nada: ese alumno queda como "facturación
-- desconocida" (null) y el margen de su profesor se marca como PARCIAL. Nunca
-- cuenta como 0 €, que sería indistinguible de un alumno que no paga.
