-- ============================================================
-- ACADEMY SCHEDULER — Schema Supabase
-- Ejecutar en: Supabase Dashboard → SQL Editor → New query
-- ============================================================

-- ── TEACHERS ────────────────────────────────────────────────
create table if not exists teachers (
  id          text primary key,
  name        text not null,
  email       text not null unique,
  avatar      text not null,
  username    text not null unique,
  password    text not null default 'profe123',
  specialties text[] default array['Inglés'],
  created_at  timestamptz default now()
);

-- ── TEACHER CALENDARS ────────────────────────────────────────
-- One row per teacher, grid stored as JSON
create table if not exists teacher_calendars (
  teacher_id  text primary key references teachers(id) on delete cascade,
  grid        jsonb not null default '{}',
  updated_at  timestamptz default now()
);

-- ── STUDENTS ─────────────────────────────────────────────────
create table if not exists students (
  id          text primary key,
  name        text not null,
  email       text not null unique,
  phone       text,
  level       text not null default 'B1',
  plan        text not null default 'Plan Individual',
  notes       text,
  -- Activación manual de suscripción: mientras esta fecha sea futura, el alumno
  -- se considera "Activa (manual)" sin consultar WooCommerce.
  manual_active_until date,
  created_at  timestamptz default now()
);

-- Para bases ya existentes:
alter table students add column if not exists manual_active_until date;
-- Tipo y nombre del producto WooCommerce (persistido para no consultar la API
-- cada vez). product_type: 'subscription' | 'one_time'.
alter table students add column if not exists product_type text;
alter table students add column if not exists product_name text;

-- ── PRODUCT MAPPINGS (horas semanales fijas por tipo de producto) ───────────
-- Detección automática de horas: si el nombre del producto CONTIENE
-- product_name_contains → weekly_hours. Debe quedar SIN RLS para que el cliente
-- (anon) pueda leerla en los formularios de asignación.
create table if not exists product_mappings (
  id                    bigint generated by default as identity primary key,
  product_name_contains text not null,
  weekly_hours          int not null
);
alter table product_mappings disable row level security;
insert into product_mappings (product_name_contains, weekly_hours)
select v.name, 4 from (values ('Intensivo FCE'), ('Intensivo PET'), ('Intensivo general'), ('Intensivo CAE')) as v(name)
where not exists (select 1 from product_mappings p where lower(p.product_name_contains) = lower(v.name));

-- ── ASSIGNMENTS ──────────────────────────────────────────────
create table if not exists assignments (
  id            text primary key,
  teacher_id    text not null references teachers(id),
  teacher_name  text not null,
  teacher_email text not null,
  student_id    text not null references students(id),
  student_name  text not null,
  student_email text not null,
  student_level text not null,
  slots         jsonb not null default '[]',   -- [{day, hour}]
  objetivo      text,
  plan          text,
  weekly_hours  int not null default 2,
  availability  text,
  notes         text,
  created_at    timestamptz default now()
);

-- ── APP USERS (setters + admins) ─────────────────────────────
create table if not exists app_users (
  id           text primary key,
  username     text not null unique,
  password     text not null,
  role         text not null check (role in ('admin','setter','teacher')),
  teacher_id   text references teachers(id),
  display_name text not null,
  created_at   timestamptz default now()
);

-- ── SEED: admin and setter users ────────────────────────────
insert into app_users (id, username, password, role, display_name) values
  ('admin1',  'admin',   'admin123',  'admin',  'Administrador'),
  ('setter1', 'setter',  'setter123', 'setter', 'Setter'),
  ('setter2', 'setter2', 'setter123', 'setter', 'Setter 2')
on conflict (username) do nothing;

-- ── SEED: 30 teachers ───────────────────────────────────────
insert into teachers (id, name, email, avatar, username, password) values
  ('t1',  'Sebastian',   'sebastian@drcacademy.com',   'SE', 'sebastian',  'profe123'),
  ('t2',  'Mauricio',    'mauricio@drcacademy.com',    'MA', 'mauricio',   'profe123'),
  ('t3',  'Johny',       'johny@drcacademy.com',       'JO', 'johny',      'profe123'),
  ('t4',  'Barbara',     'barbara@drcacademy.com',     'BA', 'barbara',    'profe123'),
  ('t5',  'Ana',         'ana@drcacademy.com',         'AN', 'ana',        'profe123'),
  ('t6',  'Ignacio',     'ignacio@drcacademy.com',     'IG', 'ignacio',    'profe123'),
  ('t7',  'Daiana.M',    'daianam@drcacademy.com',     'DM', 'daianam',    'profe123'),
  ('t8',  'Victoria',    'victoria@drcacademy.com',    'VI', 'victoria',   'profe123'),
  ('t9',  'Silvia',      'silvia@drcacademy.com',      'SI', 'silvia',     'profe123'),
  ('t10', 'Sol.G',       'solg@drcacademy.com',        'SG', 'solg',       'profe123'),
  ('t11', 'Milagros',    'milagros@drcacademy.com',    'MI', 'milagros',   'profe123'),
  ('t12', 'MFlorencia',  'mflorencia@drcacademy.com',  'MF', 'mflorencia', 'profe123'),
  ('t13', 'Sol',         'sol@drcacademy.com',         'SO', 'sol',        'profe123'),
  ('t14', 'Cristian',    'cristian@drcacademy.com',    'CR', 'cristian',   'profe123'),
  ('t15', 'DanielaN',    'danielan@drcacademy.com',    'DN', 'danielan',   'profe123'),
  ('t16', 'Rebeca',      'rebeca@drcacademy.com',      'RE', 'rebeca',     'profe123'),
  ('t17', 'Marina',      'marina@drcacademy.com',      'MR', 'marina',     'profe123'),
  ('t18', 'Jimena',      'jimena@drcacademy.com',      'JI', 'jimena',     'profe123'),
  ('t19', 'Daniela',     'daniela@drcacademy.com',     'DA', 'daniela',    'profe123'),
  ('t20', 'Antonella',   'antonella@drcacademy.com',   'AT', 'antonella',  'profe123'),
  ('t21', 'Wanda',       'wanda@drcacademy.com',       'WA', 'wanda',      'profe123'),
  ('t22', 'Luciana',     'luciana@drcacademy.com',     'LU', 'luciana',    'profe123'),
  ('t23', 'Agustin',     'agustin@drcacademy.com',     'AG', 'agustin',    'profe123'),
  ('t24', 'Liliana',     'liliana@drcacademy.com',     'LI', 'liliana',    'profe123'),
  ('t25', 'Dana',        'dana@drcacademy.com',        'DN', 'dana',       'profe123'),
  ('t26', 'Vanesa',      'vanesa@drcacademy.com',      'VN', 'vanesa',     'profe123'),
  ('t27', 'Carmela',     'carmela@drcacademy.com',     'CA', 'carmela',    'profe123'),
  ('t28', 'Chiara',      'chiara@drcacademy.com',      'CH', 'chiara',     'profe123'),
  ('t29', 'Maribel',     'maribel@drcacademy.com',     'MB', 'maribel',    'profe123'),
  ('t30', 'Daiana',      'daiana@drcacademy.com',      'DI', 'daiana',     'profe123')
on conflict (id) do nothing;

-- Link teachers to app_users
insert into app_users (id, username, password, role, teacher_id, display_name) values
  ('u_t1',  'sebastian',  'profe123', 'teacher', 't1',  'Sebastian'),
  ('u_t2',  'mauricio',   'profe123', 'teacher', 't2',  'Mauricio'),
  ('u_t3',  'johny',      'profe123', 'teacher', 't3',  'Johny'),
  ('u_t4',  'barbara',    'profe123', 'teacher', 't4',  'Barbara'),
  ('u_t5',  'ana',        'profe123', 'teacher', 't5',  'Ana'),
  ('u_t6',  'ignacio',    'profe123', 'teacher', 't6',  'Ignacio'),
  ('u_t7',  'daianam',    'profe123', 'teacher', 't7',  'Daiana M.'),
  ('u_t8',  'victoria',   'profe123', 'teacher', 't8',  'Victoria'),
  ('u_t9',  'silvia',     'profe123', 'teacher', 't9',  'Silvia'),
  ('u_t10', 'solg',       'profe123', 'teacher', 't10', 'Sol G.'),
  ('u_t11', 'milagros',   'profe123', 'teacher', 't11', 'Milagros'),
  ('u_t12', 'mflorencia', 'profe123', 'teacher', 't12', 'M. Florencia'),
  ('u_t13', 'sol',        'profe123', 'teacher', 't13', 'Sol'),
  ('u_t14', 'cristian',   'profe123', 'teacher', 't14', 'Cristian'),
  ('u_t15', 'danielan',   'profe123', 'teacher', 't15', 'Daniela N.'),
  ('u_t16', 'rebeca',     'profe123', 'teacher', 't16', 'Rebeca'),
  ('u_t17', 'marina',     'profe123', 'teacher', 't17', 'Marina'),
  ('u_t18', 'jimena',     'profe123', 'teacher', 't18', 'Jimena'),
  ('u_t19', 'daniela',    'profe123', 'teacher', 't19', 'Daniela'),
  ('u_t20', 'antonella',  'profe123', 'teacher', 't20', 'Antonella'),
  ('u_t21', 'wanda',      'profe123', 'teacher', 't21', 'Wanda'),
  ('u_t22', 'luciana',    'profe123', 'teacher', 't22', 'Luciana'),
  ('u_t23', 'agustin',    'profe123', 'teacher', 't23', 'Agustín'),
  ('u_t24', 'liliana',    'profe123', 'teacher', 't24', 'Liliana'),
  ('u_t25', 'dana',       'profe123', 'teacher', 't25', 'Dana'),
  ('u_t26', 'vanesa',     'profe123', 'teacher', 't26', 'Vanesa'),
  ('u_t27', 'carmela',    'profe123', 'teacher', 't27', 'Carmela'),
  ('u_t28', 'chiara',     'profe123', 'teacher', 't28', 'Chiara'),
  ('u_t29', 'maribel',    'profe123', 'teacher', 't29', 'Maribel'),
  ('u_t30', 'daiana',     'profe123', 'teacher', 't30', 'Daiana')
on conflict (username) do nothing;

-- ── SCORING EVENTS ──────────────────────────────────────────
create table if not exists scoring_events (
  id          text primary key,
  teacher_id  text not null references teachers(id) on delete cascade,
  event_type  text not null,
  points      int not null default 0,
  note        text,
  created_at  timestamptz default now()
);

-- ── MIGRATIONS: new columns for teachers ────────────────────
-- Run these if the teachers table already exists in your DB
alter table teachers add column if not exists internal_rating  int default 3;
alter table teachers add column if not exists score            int default 0;
alter table teachers add column if not exists is_blocked       boolean default false;
alter table teachers add column if not exists is_teacher_of_month    boolean default false;
alter table teachers add column if not exists is_teacher_of_quarter  boolean default false;
alter table teachers add column if not exists teacher_of_month_date  timestamptz;
alter table teachers add column if not exists last_monthly_reset     timestamptz;
alter table teachers add column if not exists last_quarterly_reset   timestamptz;
alter table teachers add column if not exists retention_rate         numeric default 0;
-- Correo de notificaciones (avisos de bajas, etc.). Si vacío, se usa `email`.
alter table teachers add column if not exists notification_email     text;

-- ── MIGRATIONS: webhook_logs (avisos por email) ──────────────
-- Marca si se envió el email de aviso a los profesores tras procesar el webhook.
alter table webhook_logs add column if not exists email_sent boolean default false;

-- ── MIGRATIONS: new columns for assignments ──────────────────
alter table assignments add column if not exists start_date text;
alter table assignments add column if not exists meet_link  text;

-- ── CLASS JOIN LOGS ──────────────────────────────────────────
-- Registro de ingresos a clase (clic en "Ingresar a clase")
create table if not exists class_join_logs (
  id              text primary key,
  teacher_id      text not null references teachers(id),
  teacher_name    text not null,
  student_name    text not null,
  scheduled_date  date not null,
  scheduled_time  text not null,
  clicked_at      timestamptz default now(),
  punctuality     text -- 'on_time' | 'late' | 'very_late'
);
-- Estado de suscripción WooCommerce verificado al momento del ingreso
alter table class_join_logs add column if not exists subscription_status   text;
alter table class_join_logs add column if not exists entered_without_active boolean default false;
alter table class_join_logs add column if not exists subscription_days_remaining int;
alter table class_join_logs disable row level security;

-- ── DISABLE Row Level Security for now (internal tool) ──────
alter table teachers          disable row level security;
alter table teacher_calendars disable row level security;
alter table students          disable row level security;
alter table assignments       disable row level security;
alter table app_users         disable row level security;
alter table scoring_events    disable row level security;

-- ── FINANCE: CLASS RECORDS (capturas de clase subidas por el profesor) ──────
create table if not exists class_records (
  id             text primary key,
  teacher_id     text not null references teachers(id),
  teacher_name   text not null,
  student_name   text not null,
  class_date     date not null,
  class_time     text,
  screenshot_url text not null,
  comment        text,
  created_at     timestamptz default now()
);
-- Para bases ya existentes:
alter table class_records add column if not exists comment text;
-- Tipo de clase: 'normal' | 'falta_sin_aviso' | 'cancelacion_hora' | 'recuperacion'
alter table class_records add column if not exists class_type text default 'normal';
-- Estado de suscripción WooCommerce capturado al registrar la clase manualmente.
alter table class_records add column if not exists subscription_status text;
alter table class_records disable row level security;

-- ── FINANCE: APROBACIONES MANUALES (admin aprueba a_revisar / excede_limite) ──
create table if not exists finance_manual_approvals (
  id           text primary key,
  teacher_id   text not null,
  student_name text not null,
  class_date   date not null,
  approved_by  text not null,
  approved_at  timestamptz default now(),
  reason       text
);
alter table finance_manual_approvals disable row level security;

-- ── FINANCE: RATES (4 tarifas) ──────────────────────────────────────────────
create table if not exists finance_rates (
  id         text primary key,
  plan_type  text not null,   -- 'general' | 'examenes'
  tier       text not null,   -- 'nuevo' | 'antiguo'
  rate       numeric not null
);
alter table finance_rates disable row level security;

-- ── FINANCE: PAYMENTS (liquidación mensual por profesor) ────────────────────
create table if not exists finance_payments (
  id                    text primary key,
  teacher_id            text not null references teachers(id),
  teacher_name          text not null,
  month_year            text not null,   -- 'YYYY-MM'
  total_classes_payable int default 0,
  total_amount          numeric default 0,
  bonus_amount          numeric default 0,
  status                text default 'pending',  -- 'pending' | 'paid'
  paid_at               timestamptz,
  approved_overrides    jsonb default '[]'::jsonb,
  created_at            timestamptz default now()
);
-- Para bases ya existentes (las tablas se crearon antes de añadir aprobaciones):
alter table finance_payments add column if not exists approved_overrides jsonb default '[]'::jsonb;
alter table finance_payments disable row level security;

-- ── BAJAS DE ALUMNOS (churn) ────────────────────────────────────────────────
-- Historial de alumnos que se dieron de baja. Se registra en dbDeleteStudent
-- ANTES de borrar el alumno (que hoy no deja rastro) para poder calcular una
-- retención real: retención = activos / (activos + bajas de la ventana).
-- `reason`: 'manual' (admin) | 'webhook' (suscripción cancelada) | otro.
create table if not exists student_dropouts (
  id           text primary key,
  teacher_id   text not null,
  student_id   text,
  student_name text not null,
  start_date   text,           -- inicio del alumno con el profe (si se conocía)
  dropped_at   timestamptz default now(),
  reason       text,           -- 'manual' | 'webhook'
  created_by   text
);
create index if not exists idx_student_dropouts_teacher on student_dropouts(teacher_id);
create index if not exists idx_student_dropouts_dropped_at on student_dropouts(dropped_at);
alter table student_dropouts disable row level security;
