-- ─────────────────────────────────────────────────────────────────────────────
-- PENDIENTES DETECTADOS EN LA AUDITORÍA DEL 24/07/2026
--
-- Tres tablas y dos columnas que el código YA usa y que nunca se crearon en
-- producción. Todo es aditivo: no borra ni modifica ninguna fila existente.
-- Es un extracto de supabase-schema.sql + supabase-churn.sql, sin cambios en el
-- DDL — verificado columna por columna contra los inserts del código.
--
-- Idempotente: se puede correr dos veces sin efecto.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1. student_dropouts ──────────────────────────────────────────────────────
-- Historial de bajas. Se registra en dbDeleteStudent (lib/db.ts:1064) ANTES de
-- borrar al alumno. Sin esta tabla la baja no deja rastro y calcRetentionRate
-- devuelve siempre 100 % (retención = activos / (activos + bajas)).
create table if not exists student_dropouts (
  id           text primary key,
  teacher_id   text not null,
  student_id   text,
  student_name text not null,
  start_date   text,           -- inicio del alumno con el profe (si se conocía)
  dropped_at   timestamptz default now(),
  reason       text,           -- 'manual' | 'webhook'
  created_by   text
);
create index if not exists idx_student_dropouts_teacher    on student_dropouts(teacher_id);
create index if not exists idx_student_dropouts_dropped_at on student_dropouts(dropped_at);
alter table student_dropouts disable row level security;


-- ── 2. churn_snapshots ───────────────────────────────────────────────────────
-- Fotos de señales de riesgo por alumno (lib/churnSnapshot.ts:82). El código ya
-- tolera su ausencia (chequea PGRST205 y sigue), así que hoy calcula el riesgo y
-- lo tira: no acumula dataset.
create table if not exists churn_snapshots (
  id                    text primary key,
  student_id            text,
  student_name          text not null,
  teacher_id            text,
  captured_at           timestamptz default now(),
  trigger               text,          -- 'cancellation' | 'active_check' | 'manual'
  label                 text,          -- 'churned' | 'active'

  classes_analyzed      int,
  -- señales deterministas
  cancellations         int,
  late_count            int,
  risk_flags            int,
  days_since_last_class int,
  avg_speaking_pct      int,
  speaking_trend        text,          -- 'up' | 'stable' | 'down' | 'unknown'
  deterministic_risk    int,
  -- señales por IA
  ai_risk_score         int,
  ai_participation      text,
  ai_explicit_quit      boolean,
  ai_reasoning          text,
  -- riesgo combinado + volcado completo para análisis futuro
  combined_risk         int,
  alerted               boolean default false,
  signals               jsonb,
  ai_raw                jsonb
);
create index if not exists idx_churn_student  on churn_snapshots (student_id);
create index if not exists idx_churn_label    on churn_snapshots (label);
create index if not exists idx_churn_captured on churn_snapshots (captured_at desc);
alter table churn_snapshots disable row level security;


-- ── 3. product_mappings ──────────────────────────────────────────────────────
-- Mapeo nombre de producto → horas semanales (PASO 4 de detectWeeklyHours,
-- lib/productUtils.ts). Hoy la consulta falla dentro de un try/catch silencioso y
-- la detección de horas cae directo a "completar manualmente".
create table if not exists product_mappings (
  id                    bigint generated by default as identity primary key,
  product_name_contains text not null,
  weekly_hours          int not null
);
alter table product_mappings disable row level security;

-- Semilla (solo inserta lo que falta).
insert into product_mappings (product_name_contains, weekly_hours)
select v.name, 4
from (values ('Intensivo FCE'), ('Intensivo PET'), ('Intensivo general'), ('Intensivo CAE')) as v(name)
where not exists (
  select 1 from product_mappings p
  where lower(p.product_name_contains) = lower(v.name)
);


-- ── 4. students.product_type / product_name ──────────────────────────────────
-- Producto de WooCommerce persistido. Sin estas columnas, check-subscription
-- intenta guardarlo en cada consulta y falla en silencio (route.ts:255), así que
-- nada se cachea y stu.productName es SIEMPRE undefined — pese a ser la fuente
-- primaria de resolución de plan en lib/finance.ts.
-- Columna nueva y nullable: en PostgreSQL es cambio de metadatos, sin reescribir
-- la tabla.
alter table students add column if not exists product_type text;
alter table students add column if not exists product_name text;


-- ── VERIFICACIÓN (correr después; debe devolver 5 filas en 'ok') ─────────────
-- select 'student_dropouts' as objeto,
--        to_regclass('public.student_dropouts') is not null as ok
-- union all select 'churn_snapshots',  to_regclass('public.churn_snapshots') is not null
-- union all select 'product_mappings', to_regclass('public.product_mappings') is not null
-- union all select 'students.product_type', exists (
--   select 1 from information_schema.columns
--   where table_name='students' and column_name='product_type')
-- union all select 'students.product_name', exists (
--   select 1 from information_schema.columns
--   where table_name='students' and column_name='product_name');
