import { Teacher, Student, AdminAlert } from '@/types';

export const mockTeachers: Teacher[] = [
  {
    id: 't1',
    name: "Sebastian",
    email: "sebastian@drcacademy.com",
    avatar: "SE",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't2',
    name: "Mauricio",
    email: "mauricio@drcacademy.com",
    avatar: "MA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't3',
    name: "Johny",
    email: "johny@drcacademy.com",
    avatar: "JO",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't4',
    name: "Barbara",
    email: "barbara@drcacademy.com",
    avatar: "BA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't5',
    name: "Ana",
    email: "ana@drcacademy.com",
    avatar: "AN",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't6',
    name: "Ignacio",
    email: "ignacio@drcacademy.com",
    avatar: "IG",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't7',
    name: "Daiana.M",
    email: "daianam@drcacademy.com",
    avatar: "DM",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't8',
    name: "Victoria",
    email: "victoria@drcacademy.com",
    avatar: "VI",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't9',
    name: "Silvia",
    email: "silvia@drcacademy.com",
    avatar: "SI",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't10',
    name: "Sol.G",
    email: "solg@drcacademy.com",
    avatar: "SG",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't11',
    name: "Milagros",
    email: "milagros@drcacademy.com",
    avatar: "MI",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't12',
    name: "MFlorencia",
    email: "mflorencia@drcacademy.com",
    avatar: "MF",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't13',
    name: "Sol",
    email: "sol@drcacademy.com",
    avatar: "SO",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't14',
    name: "Cristian",
    email: "cristian@drcacademy.com",
    avatar: "CR",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't15',
    name: "DanielaN",
    email: "danielan@drcacademy.com",
    avatar: "DA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't16',
    name: "Rebeca",
    email: "rebeca@drcacademy.com",
    avatar: "RE",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't17',
    name: "Marina",
    email: "marina@drcacademy.com",
    avatar: "MA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't18',
    name: "Jimena",
    email: "jimena@drcacademy.com",
    avatar: "JI",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't19',
    name: "Daniela",
    email: "daniela@drcacademy.com",
    avatar: "DA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't20',
    name: "Antonella",
    email: "antonella@drcacademy.com",
    avatar: "AN",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't21',
    name: "Wanda",
    email: "wanda@drcacademy.com",
    avatar: "WA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't22',
    name: "Luciana",
    email: "luciana@drcacademy.com",
    avatar: "LU",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't23',
    name: "Agustin",
    email: "agustin@drcacademy.com",
    avatar: "AG",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't24',
    name: "Liliana",
    email: "liliana@drcacademy.com",
    avatar: "LI",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't25',
    name: "Dana",
    email: "dana@drcacademy.com",
    avatar: "DA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't26',
    name: "Vanesa",
    email: "vanesa@drcacademy.com",
    avatar: "VA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't27',
    name: "Carmela",
    email: "carmela@drcacademy.com",
    avatar: "CA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't28',
    name: "Chiara",
    email: "chiara@drcacademy.com",
    avatar: "CH",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't29',
    name: "Maribel",
    email: "maribel@drcacademy.com",
    avatar: "MA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
  {
    id: 't30',
    name: "Daiana",
    email: "daiana@drcacademy.com",
    avatar: "DA",
    status: 'no_availability',
    weeklyLoad: 0,
    maxWeeklyLoad: 20,
    freeSpots: 0,
    totalSpots: 0,
    nextClass: undefined,
    specialties: ['Inglés'],
    timeSlots: [],
    blockedSlots: [],
    vacations: [],
    upcomingClasses: [],
  },
];

export const mockStudents: Student[] = [
  { id: 's1', name: "Angel Guillermo", email: "angel.guillermo@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's2', name: "Jorge Fernandez", email: "jorge.fernandez@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's3', name: "Sira Jiménez de la Torre", email: "sira.jimenez.de.la.torre@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's4', name: "Macarena Llosa", email: "macarena.llosa@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's5', name: "Nicolas Martín", email: "nicolas.martin@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's6', name: "María José Cabrera", email: "maria.jose.cabrera@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's7', name: "María Sarai Irvene", email: "maria.sarai.irvene@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's8', name: "Sara Troncoso", email: "sara.troncoso@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's9', name: "Clara Valor Valencia", email: "clara.valor.valencia@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's10', name: "Javier Otero Nieto", email: "javier.otero.nieto@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's11', name: "Rafael Collado Verdejo", email: "rafael.collado.verdejo@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's12', name: "Aleix Ollé Espigares", email: "aleix.olle.espigares@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's13', name: "Monserrat Muñoz", email: "monserrat.munoz@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's14', name: "Nuria Ruiz Pinto", email: "nuria.ruiz.pinto@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's15', name: "Gracia Fernández Luque", email: "gracia.fernandez.luque@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's16', name: "Diego Ruiz Martín", email: "diego.ruiz.martin@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's17', name: "Guillem Albert Baldrich", email: "guillem.albert.baldrich@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's18', name: "Alvaro Jabon Gomez", email: "alvaro.jabon.gomez@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's19', name: "Elisa Sáenz Gómez", email: "elisa.saenz.gomez@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
  { id: 's20', name: "Lucía Pérez Bez", email: "lucia.perez.bez@alumnos.drc.com", level: 'B1', plan: 'Plan Individual', createdAt: '2025-01-01T00:00:00Z' },
];

export const mockAlerts: AdminAlert[] = [
  { id: 'a1', type: 'conflict', message: 'Marina y MFlorencia sin cupos disponibles esta semana', severity: 'high' },
  { id: 'a2', type: 'conflict', message: 'Agustín supera 40 clases semanales — revisar carga', severity: 'high' },
  { id: 'a3', type: 'coverage', message: 'Johny sin disponibilidad cargada — pendiente actualización', severity: 'medium' },
  { id: 'a4', type: 'coverage', message: 'Rebeca: solo 4 clases asignadas — baja actividad', severity: 'medium' },
  { id: 'a5', type: 'warning', message: 'Antonella y Liliana con menos del 10% de cupos libres', severity: 'medium' },
];

export const daysOfWeek = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];

export const timeSlotOptions = [
  '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00',
  '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00',
];

export const classTypes = [
  'B2 First', 'IELTS', 'TOEFL', 'C1 Advanced', 'B1 Preliminary',
  'Business English', 'Conversación', 'Gramática', 'Pronunciación',
  'Academic English', 'Teens', 'Kids',
];
